# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='service_required',
            field=models.CharField(choices=[('Male Nurse', 'Male Nurse'), ('Female Nurse', 'Female Nurse'), ('Baby Sitter', 'Babysitter'), ('Physiotherapist', 'physiotherapist')], default='Male Nurse', max_length=20),
        ),
    ]
