# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170215_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('prescribed_by', models.CharField(max_length=50)),
                ('prescription_date', models.DateField()),
                ('prescription_image', models.FileField(upload_to='')),
            ],
        ),
    ]
