# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_prescriptiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('service_required', models.CharField(choices=[('MN', 'Male Nusrse'), ('FN', 'Female Nusrse'), ('BS', 'Babysitter'), ('PS', 'Physiotherapist')], default=' ', max_length=20)),
                ('duration', models.CharField(choices=[('8hrs', '8hrs/day'), ('12hrs', '12hrs/day'), ('16hrs', '16hrs/day'), ('24hrs', '24hrs/day')], default=' ', max_length=20)),
                ('period', models.CharField(choices=[('7day', '7days'), ('15day', '15days'), ('30day', '30days')], default=' ', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
