# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_packagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedata',
            name='service_required',
            field=models.CharField(choices=[('MN', 'Male Nurse'), ('FN', 'Female Nurse'), ('BS', 'Babysitter'), ('PS', 'Physiotherapist')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptiondata',
            name='prescription_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
